apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate-prometheus
  namespace: default
spec:
  metrics:
  - name: nginx-5xx-errors
    interval: 30s
    count: 1
    successCondition: result[0] < 1
    failureCondition: result[0] >= 1
    provider:
      prometheus:
        address: http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090
        query: |
          sum(rate(nginx_ingress_controller_requests{status=~"5.."}[1m]))
